### PR TITLE
Add field errors to registration form template

### PR DESCRIPTION
**Pull request by tbrlpld**
Before, it was possible to enter invalid data into the registration
form, e.g. duplicate username, insecure password, etc., without being
notified about the violation. The form would simply reload and no user
is created and no email is sent.

Without being notified about the registration form issue, one might
assume that something in the setup is not correct and waste hours
trying to debug something that is not broken. At least, that is what
happened to me 😬

This commit adds the form field errors to the registration form
template.

This change has been discussed with @bbelderbos view email.

### CODE REVIEW

**Comment by bbelderbos** [comment]
Thanks a lot @tbrlpld it's hard to see the diff here so I downloaded the new zip file and compared it with what I had, seems you only updated django_registration/registration_form.html with these changes right?

Screenshot 2019-12-30 at 21 11 05

**Comment by tbrlpld** [comment]
@bbelderbos Yes, that was the only form where I was having the issue. Errors in the login form seem to be caught and displayed as above the form like other "non field errors" would. So no need to change that.

**Comment by bbelderbos** [comment]
@tbrlpld great I am seeing it locally now too so merging the fix. As discussed also pinning Django requirements to 2.2 till django-registration becomes compatible with 3.x (issue https://github.com/ubernostrum/django-registration/issues/191) - thanks

**Comment by tbrlpld** [comment]
Thank you for the merge! Hope this will help some other students in the future :)

**Comment by mikeckennedy** [comment]
Thank you both for keeping this one fresh.

**Pull request merged**
